name: SerializerSharp Publish Nuget

# [push] git push [create] git push <tag>
#on: [create]
on: 
  create:
    tags:
      - 'v*'
jobs:
  publish:
    name: Publish Project to Nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.403 # SDK Version to use.
    - name: Build
      run: |
        version="$(git describe --tags)".trimstart("v")
        dotnet build SerializerSharp --configuration release -p:PackageVersion=$version
        echo "::set-env name=PKGPATH::$(find /home/runner/work/SerializerSharp/SerializerSharp/SerializerSharp/bin/release/ -name "*.nupkg")" # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
    - name: Publish
      run: dotnet nuget push ${PKGPATH} -k ${APIKEY} -s https://api.nuget.org/v3/index.json
      env:
        APIKEY: ${{ secrets.APPKEY }}
