name: SerializerSharp Publish Nuget

# [push] git push [create] git push <tag>
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.403 # SDK Version to use.
    - name: Build with dotnet
      run: dotnet build SerializerSharp --configuration Release
  publish:
    needs: [build]
    name: Publish Project to Nuget
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.403 # SDK Version to use.
    - name: Publish
      #run: |
        #version=`git describe --tags`
        #dotnet pack SerializerSharp --configuration release -p:PackageVersion=$version
        #dotnet nuget push SerializerSharp/bin/Release/SerializerSharp.$version.nupkg -k ${APIKEY} -s https://api.nuget.org/v3/index.json
      run: |
        dotnet build SerializerSharp --configuration release
        dotnet nuget push 'SerializerSharp/bin/Release/SerializerSharp.*.nupkg' -k ${APIKEY} -s https://api.nuget.org/v3/index.json
      env:
        APIKEY: ${{ secrets.APPKEY }}
